---
- name: "restart opensearch-docker"
  community.docker.docker_compose_v2:
    project_src: "{{ opensearch_docker_compose_dir }}"
    state: restarted
    timeout: 60
  when: not r_opensearch_start_result.changed
