---
vector_docker_version: "0.51.1-alpine"
vector_docker_tag: "{{ vector_docker_version }}"
vector_docker_image: "timberio/vector:{{ vector_docker_tag }}"
vector_docker_instance: ""
vector_docker_timezone: "{{ timezone_name | default('UTC') }}"
vector_docker_compose_extra_conf: {}
vector_docker_bind_mount_volumes: true
vector_docker_extra_volumes: []
vector_docker_data_dir: "{{ vector_docker_compose_dir }}/data"


### vector -------------------------------------------------------------------------------------------------------------
vector_docker_config:
