---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - spilo
    - validate


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - spilo


- name: "Dynamic Configuration Settings"
  ansible.builtin.include_tasks: "dcs.yml"
  tags:
    - spilo


- name: "Extra users"
  ansible.builtin.include_tasks: "extra_users.yml"
  when: spilo_docker_extra_users | length > 0
  tags:
    - spilo


- name: "Verify"
  ansible.builtin.include_tasks: "verify.yml"
  tags:
    - spilo
    - verify
