---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - spilo
    - validate


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - spilo
    - install


- name: "Dynamic Configuration Settings"
  ansible.builtin.include_tasks: "dcs.yml"
  tags:
    - spilo
    - dcs


- name: "Extra users"
  ansible.builtin.include_tasks: "extra_users.yml"
  when: spilo_docker_extra_users | length > 0
  tags:
    - spilo
    - extra_users


- name: "SQL queries"
  ansible.builtin.include_tasks: "sql_queries.yml"
  when: spilo_docker_extra_users | length > 0
  tags:
    - spilo
    - sql_queries


- name: "Verify"
  ansible.builtin.include_tasks: "verify.yml"
  tags:
    - spilo
    - verify
