---
- name: "Ensure that variable is string"
  ansible.builtin.assert:
    that: vars[item] | type_debug in ["str", "string", "AnsibleUnicode", "AnsibleUnsafeText", "AnsibleVaultEncryptedUnicode"]
    quiet: true
    fail_msg: "The variable must be a string"
  loop:
    - spilo_docker_version
    - spilo_docker_tag
    - spilo_docker_image
    - spilo_docker_instance
    - spilo_docker_timezone
    - spilo_docker_data_dir
    - spilo_docker_cluster_name
    - spilo_docker_superuser_name
    - spilo_docker_superuser_pass
  tags:
    - spilo
    - validate


- name: "Ensure that variable is integer"
  ansible.builtin.assert:
    that: lookup('ansible.builtin.vars', item) | string | regex_search("^[0-9]+$") is not none
    quiet: true
    fail_msg: "Variable must be an integer"
  loop:
    - spilo_docker_uid
    - spilo_docker_gid
    - spilo_docker_postgresql_listen_port
    - spilo_docker_patroni_restapi_listen_port
  tags:
    - spilo
    - validate


- name: "Ensure that variable is boolean"
  ansible.builtin.assert:
    that: vars[item] | type_debug == "bool"
    quiet: true
    fail_msg: "The variable must be a boolean"
  loop:
    - spilo_docker_bind_mount_volumes
  tags:
    - spilo
    - validate


- name: "Ensure that variable is list"
  ansible.builtin.assert:
    that: vars[item] | type_debug in ["list", "AnsibleSequence"]
    quiet: true
    fail_msg: "The variable must be a list"
  loop:
    - spilo_docker_extra_volumes
    - spilo_docker_extra_users
    - spilo_docker_sql_queries
  tags:
    - spilo
    - validate


- name: "Ensure that variable is dict"
  ansible.builtin.assert:
    that: vars[item] is mapping
    quiet: true
    fail_msg: "The variable must be a dictionary"
  loop:
    - spilo_docker_compose_extra_conf
    - spilo_docker_dcs_conf
    - spilo_docker_environment
    - spilo_docker_env_default
  tags:
    - spilo
    - validate
