---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - postgresql
    - validate


- name: "Set facts"
  ansible.builtin.include_tasks: "set_facts.yml"
  tags:
    - postgresql


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - postgresql


- name: "Verify"
  ansible.builtin.include_tasks: "verify.yml"
  when: not ansible_check_mode
  tags:
    - postgresql
    - verify


- name: "Extra users"
  ansible.builtin.include_tasks: "extra_users.yml"
  when: postgresql_extra_users | length > 0
  tags:
    - postgresql
