---
docker_ce_remove_packages:
  - "docker"
  - "docker-engine"
  - "docker.io"
  - "containerd"
  - "runc"

docker_ce_install_packages:
  - "{{ 'docker-ce=' + docker_ce_version if docker_ce_version else 'docker-ce' }}"
  - "docker-compose-plugin"
  - "docker-buildx-plugin"
