---
docker_ce_version: ""

### systemd ------------------------------------------------------------------------------------------------------------
docker_ce_systemd_environment: {}
docker_ce_systemd_requires: []

### daemon.json --------------------------------------------------------------------------------------------------------
docker_ce_config: {}
