---
spilo_version: "17"
spilo_docker_tag: "latest"
spilo_docker_image: "ghcr.io/zalando/spilo-{{ spilo_version }}:{{ spilo_docker_tag }}"
spilo_docker_instance: "{{ spilo_version }}"
spilo_docker_uid: 101
spilo_docker_gid: 103
spilo_docker_timezone: "{{ timezone_name }}"
spilo_docker_compose_extra_conf: {}
spilo_docker_bind_mount_volumes: true
spilo_docker_extra_volumes: []
spilo_docker_data_dir: "{{ spilo_docker_compose_dir }}/data"


spilo_docker_environment: {}
spilo_docker_env_default:
  SCOPE: "spilo-docker-cluster"
  ETCD3_HOSTS: "127.0.0.1:2379"
