---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - opensearch
    - validate


- name: "Set facts"
  ansible.builtin.include_tasks: "set_facts.yml"
  tags:
    - opensearch


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - opensearch


- name: "Verify"
  ansible.builtin.include_tasks: "verify.yml"
  when: not ansible_check_mode
  tags:
    - opensearch
    - verify


- name: "Configure"
  ansible.builtin.include_tasks: "configure.yml"
  tags:
    - opensearch
