---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - opensearch
    - validate


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - opensearch


- name: "Verify"
  ansible.builtin.include_tasks: "verify.yml"
  when: not ansible_check_mode
  tags:
    - opensearch
    - verify
